version: "3.8"
services:
#  init:
#    restart: "no"
#    command:
#      - "-init=true"
#      - "-tracerId=/p2p/trid"
#    build:
#      context: ./
#      dockerfile: publisher.Dockerfile
#    volumes:
#      - ./volume:/p2p
#    networks:
#      vpcbr:

  tracer1:
    healthcheck:
      test: [ "CMD", "test", "-f", "/p2p/data/current" ]
      interval: 3s
      timeout: 1s
      retries: 3
      start_period: 10s

    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    volumes:
      - ./volume:/p2p
      - ./volume/data/json:/tmp
    command:
      - "-json=/tmp"
      - "-dir=/p2p/data"
      - "-id=/p2p/trid"
    build:
      context: ./
      dockerfile: tracer.Dockerfile

  publisher1:
    restart: always
    depends_on:
      tracer1:
        condition: service_healthy
    command:
      - "-topic=pub-topic-1"
      - "-id=pub-1"
      - "-tracerAddr=10.5.0.6"
      - "-tracerPort=4001"
      - "-tracerId=/p2p/trid"
    build:
      context: ./
      dockerfile: publisher.Dockerfile
    volumes:
      - ./volume:/p2p
    networks:
      vpcbr:

  publisher2:
    restart: always
    depends_on:
      tracer1:
        condition: service_healthy
    command:
      - "-topic=pub-topic-2"
      - "-id=pub-2"
      - "-tracerAddr=10.5.0.6"
      - "-tracerPort=4001"
      - "-tracerId=/p2p/trid"
    build:
      context: ./
      dockerfile: publisher.Dockerfile
    volumes:
      - ./volume:/p2p
    networks:
      vpcbr:

  consumers:
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 30
      resources:
        limits:
          cpus: '0.50'
          memory: 50M

    depends_on:
      - publisher1
      - publisher2
    command:
      - "-agent=true"
      - "-tracerAddr=10.5.0.6"
      - "-tracerPort=4001"
      - "-tracerId=/p2p/trid"
    build:
      context: ./
      dockerfile: publisher.Dockerfile
    volumes:
      - ./volume:/p2p
    networks:
      vpcbr:

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1